# Generated by Django 4.2.3 on 2023-07-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='image',
            field=models.ImageField(default=1, upload_to='Photos/jobs/%y/%m/%d'),
            preserve_default=False,
        ),
    ]
