# Generated by Django 4.2.3 on 2023-07-11 16:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0003_alter_job_image'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='job',
            unique_together={('user', 'title')},
        ),
    ]
