# Generated by Django 4.2.3 on 2023-07-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_alter_job_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name=(('programming', 'programming'), ('design', 'design'), ('mangement', 'mangement'))),
        ),
    ]
