# Generated by Django 4.2.3 on 2023-07-15 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_job_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='category',
            field=models.CharField(blank=True, choices=[('programming', 'programming'), ('design', 'design'), ('mangement', 'mangement')], max_length=50, null=True),
        ),
    ]
